spring.cloud.stream:
  function.definition: domainProcessor
  bindings:
    domainProcessor-in-0:
      destination: movie-tweets-topic # Use the existing topic name
    domainProcessor-out-0:
      destination: salaar-topic
    domainProcessor-out-1:
      destination: dunki-topic
  kafka:
    bindings:
      domainProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer # Use StringDeserializer
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.apache.kafka.common.serialization.StringSerializer # Use StringSerializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092
